// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore Generated by the OpenNext build before Wrangler bundles this file.
import handler from "./.open-next/worker.js";
import PostalMime from "postal-mime";

type EmailQueueBody = { ingestionId: string };
type QueueBinding<T> = { send(body: T, options?: { contentType?: "json" }): Promise<void> };
type QueueMessage<T> = { body: T; attempts: number; ack(): void; retry(options?: { delaySeconds?: number }): void };
type MessageBatch<T> = { messages: Array<QueueMessage<T>> };
type IncomingEmailMessage = {
  from: string;
  to: string;
  headers: Headers;
  raw: ReadableStream;
  rawSize: number;
  setReject(reason: string): void;
};

interface GainingDocxEnv {
  WORKER_SELF_REFERENCE: { fetch(request: Request): Promise<Response> };
  CRON_SECRET: string;
  EMAIL_INGEST_DOMAIN: string;
  EMAIL_INGESTION_QUEUE: QueueBinding<EmailQueueBody>;
}

function isPrivateIntakeAddress(value: string, domain: string) {
  const escapedDomain = domain.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`^[a-z0-9]{24,64}@${escapedDomain}$`, "i").test(value.trim());
}

function base64(value: ArrayBuffer | Uint8Array | string) {
  if (typeof value === "string") return Buffer.from(value).toString("base64");
  return Buffer.from(value instanceof Uint8Array ? value : new Uint8Array(value)).toString("base64");
}

function canonicalRedirect(request: Request) {
  const url = new URL(request.url);
  const isCanonicalHost = url.hostname === "gainingdocx.com";
  const isHttps = url.protocol === "https:";

  if (isCanonicalHost && isHttps) return null;

  // Only normalize the two public production hosts. Preview and workers.dev
  // hosts must keep working for deployment checks.
  if (url.hostname !== "www.gainingdocx.com" && !isCanonicalHost) return null;

  url.protocol = "https:";
  url.hostname = "gainingdocx.com";
  url.port = "";
  return Response.redirect(url.toString(), 308);
}

export default {
  async fetch(
    request: Request,
    env: Parameters<typeof handler.fetch>[1] & {
      ASSETS: { fetch(request: Request): Promise<Response> };
    },
    ctx: Parameters<typeof handler.fetch>[2]
  ) {
    const redirect = canonicalRedirect(request);
    if (redirect) return redirect;

    const pathname = new URL(request.url).pathname;

    // Downloadable office files are useful resources, not HTML search-result
    // pages. Make that intent explicit instead of leaving Google to classify
    // each binary as "crawled - currently not indexed".
    if (pathname.startsWith("/downloads/")) {
      const response = await env.ASSETS.fetch(request);
      const headers = new Headers(response.headers);
      headers.set("X-Robots-Tag", "noindex");
      return new Response(response.body, {
        status: response.status,
        statusText: response.statusText,
        headers,
      });
    }

    return handler.fetch(request, env, ctx);
  },
  async scheduled(_event: unknown, env: GainingDocxEnv, ctx: { waitUntil(task: Promise<unknown>): void }) {
    const request = new Request("https://gainingdocx.internal/api/cron/charge-alerts", {
      method: "POST",
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(env.WORKER_SELF_REFERENCE.fetch(request));
  },
  async email(message: IncomingEmailMessage, env: GainingDocxEnv) {
    const domain = env.EMAIL_INGEST_DOMAIN || "docs.gainingdocx.com";
    if (!isPrivateIntakeAddress(message.to, domain)) {
      message.setReject("Unknown GainingDocx intake address");
      return;
    }
    if (message.rawSize > 25 * 1024 * 1024) {
      message.setReject("Message exceeds the 25 MiB intake limit");
      return;
    }

    const parsed = await PostalMime.parse(message.raw, { attachmentEncoding: "arraybuffer" });
    const attachments = parsed.attachments.slice(0, 20).map((attachment, index) => ({
      filename: attachment.filename || `attachment-${index + 1}`,
      contentType: attachment.mimeType,
      content: base64(attachment.content),
    }));
    const response = await env.WORKER_SELF_REFERENCE.fetch(new Request("https://gainingdocx.internal/api/internal/email-in/accept", {
      method: "POST",
      headers: { Authorization: `Bearer ${env.CRON_SECRET}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        messageId: parsed.messageId || message.headers.get("message-id") || crypto.randomUUID(),
        from: message.from,
        to: message.to,
        subject: parsed.subject || message.headers.get("subject") || "Shipment documents",
        attachments,
      }),
    }));
    const result = await response.json().catch(() => null) as { ingestionId?: string; error?: string } | null;
    if (!response.ok || !result?.ingestionId) {
      message.setReject(result?.error || "GainingDocx could not accept this document set");
      return;
    }
    await env.EMAIL_INGESTION_QUEUE.send({ ingestionId: result.ingestionId }, { contentType: "json" });
  },
  async queue(batch: MessageBatch<EmailQueueBody>, env: GainingDocxEnv) {
    for (const message of batch.messages) {
      try {
        const response = await env.WORKER_SELF_REFERENCE.fetch(new Request("https://gainingdocx.internal/api/internal/email-in/process", {
          method: "POST",
          headers: { Authorization: `Bearer ${env.CRON_SECRET}`, "Content-Type": "application/json" },
          body: JSON.stringify(message.body),
        }));
        if (!response.ok) throw new Error(`Email ingestion returned ${response.status}`);
        message.ack();
      } catch {
        message.retry({ delaySeconds: Math.min(300, 15 * Math.max(1, message.attempts)) });
      }
    }
  },
};
