// @ts-ignore Generated by the OpenNext build before Wrangler bundles this file.
import handler from "./.open-next/worker.js";

interface GainingDocxEnv {
  WORKER_SELF_REFERENCE: { fetch(request: Request): Promise<Response> };
  CRON_SECRET: string;
}

export default {
  fetch: handler.fetch,
  async scheduled(_event: unknown, env: GainingDocxEnv, ctx: { waitUntil(task: Promise<unknown>): void }) {
    const request = new Request("https://gainingdocx.internal/api/cron/charge-alerts", {
      method: "POST",
      headers: { Authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(env.WORKER_SELF_REFERENCE.fetch(request));
  },
};
