import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Calculator, CheckCircle2, Container, FileSearch, Mail, Ship, TimerReset, Upload } from "lucide-react";

import { Button } from "@/components/ui/button";
import { FreightModeTag } from "@/components/ui/freight-mode-tag";
import { JsonLd, breadcrumbLd } from "@/lib/seo/jsonld";
import { FLAGSHIP_WORKFLOWS, workflowLaunchHref } from "@/lib/workflows/flagship";

export const metadata: Metadata = {
  title: "Ocean Freight Document Automation",
  description: "Forward or upload bookings, shipping instructions, Bills of Lading, invoices, packing lists, arrival notices and container evidence for connected ocean-freight checks.",
  alternates: { canonical: "/ocean-freight" },
};

const oceanWorkflows = FLAGSHIP_WORKFLOWS.filter((workflow) => workflow.mode === "ocean");

export default function OceanFreightPage() {
  return <>
    <JsonLd data={breadcrumbLd([{ name: "Home", path: "/" }, { name: "Ocean freight", path: "/ocean-freight" }])} />

    <section className="relative overflow-hidden bg-brand-deep">
      <div
        className="pointer-events-none absolute inset-0"
        aria-hidden
        style={{ backgroundImage: "radial-gradient(ellipse 70% 60% at 8% 0%, rgba(47,109,240,0.42), transparent 62%), radial-gradient(ellipse 55% 55% at 96% 12%, rgba(255,199,0,0.16), transparent 60%)" }}
      />
      <div className="relative mx-auto grid max-w-6xl items-center gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:py-24">
        <div><div className="flex flex-wrap items-center gap-2"><FreightModeTag mode="ocean" /><span className="text-xs font-semibold uppercase tracking-[0.14em] text-amber">Ocean freight paperwork workspace</span></div><h1 className="mt-5 max-w-3xl text-4xl font-extrabold leading-[1.06] tracking-[-0.035em] text-white sm:text-5xl lg:text-[3.4rem]">Ocean paperwork from booking to release—without an air-cargo detour.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">Work with the correct ocean evidence: booking confirmation, shipping instructions, draft or final B/L, container and packing data, arrival notice, last free day and D&amp;D invoice.</p><div className="mt-7 flex flex-col gap-3 sm:flex-row"><Button render={<Link href="/app/ocean-freight" />} size="lg" className="h-12 bg-amber px-6 font-semibold text-brand-deep hover:bg-amber/90">Open ocean workspace <ArrowRight aria-hidden /></Button><Button render={<Link href="/app/email-in" />} size="lg" variant="outline" className="h-12 border-white/25 bg-white/5 px-6 font-semibold text-white hover:bg-white/15 hover:text-white"><Mail aria-hidden /> Get email-in address</Button></div><p className="mt-4 text-xs leading-5 text-white/55">Decision-support only. Carrier, terminal, customs and contractual records remain authoritative.</p></div>
        <div className="overflow-hidden rounded-2xl border border-amber/45 bg-card shadow-panel"><div className="flex items-center justify-between bg-brand-deep px-5 py-4 text-white"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-white/10"><Ship className="size-5" aria-hidden /></span><div><p className="text-[0.68rem] uppercase tracking-[0.12em] text-white/60">Ocean export set</p><p className="font-semibold">Booking → SI → Draft B/L</p></div></div><FreightModeTag mode="ocean" /></div><div className="space-y-2.5 p-5 sm:p-6">{["Booking and B/L route agree", "Container and seal references checked", "Freight terms need review", "Last-free-day evidence kept separate"].map((item, index) => <div key={item} className="flex items-center gap-3 rounded-xl border border-border bg-surface-alt p-3"><span className={`flex size-7 shrink-0 items-center justify-center rounded-full text-xs font-bold ${index < 2 ? "bg-positive-soft text-positive" : "bg-amber-soft text-amber-ink"}`}>{index < 2 ? "✓" : "!"}</span><p className="text-sm font-medium text-foreground">{item}</p></div>)}</div></div>
      </div>
    </section>

    <section className="section-edge bg-primary text-white" aria-label="Ocean document intake options"><div className="mx-auto grid max-w-6xl gap-4 px-4 py-8 sm:grid-cols-[1fr_auto_1fr] sm:items-center sm:px-6"><div className="flex items-start gap-3"><Mail className="mt-1 size-6 shrink-0 text-amber" aria-hidden /><div><p className="font-extrabold">Forward by email</p><p className="mt-1 text-sm text-white/70">Best for carrier drafts, arrival notices and recurring document traffic.</p></div></div><span className="hidden text-sm font-extrabold text-white/40 sm:block">OR</span><div className="flex items-start gap-3"><Upload className="mt-1 size-6 shrink-0 text-amber" aria-hidden /><div><p className="font-extrabold">Upload manually</p><p className="mt-1 text-sm text-white/70">Best for controlled booking, export and arrival review sets.</p></div></div></div></section>

    <section className="section-edge bg-white"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-signal">Ocean-specific operating flow</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-brand-deep sm:text-4xl">Choose the ocean job you are completing.</h2><p className="mt-4 leading-7 text-muted-foreground">The workflow asks for ocean evidence only. Shared commercial documents appear when they are actually needed for a cross-check.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2">{oceanWorkflows.map((workflow) => <article key={workflow.key} className="flex flex-col rounded-3xl border border-amber/45 bg-background p-6"><div className="flex items-center justify-between"><span className="flex size-11 items-center justify-center rounded-2xl bg-primary text-white"><Ship className="size-5" aria-hidden /></span><FreightModeTag mode="ocean" /></div><h3 className="mt-5 text-xl font-extrabold text-brand-deep">{workflow.name}</h3><p className="mt-2 text-sm font-bold">{workflow.sequence}</p><p className="mt-3 flex-1 text-sm leading-6 text-muted-foreground">{workflow.outcome}</p><Link href={workflowLaunchHref(workflow.key)} className="mt-5 inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-bold text-white">Start ocean workflow <ArrowRight className="size-4" aria-hidden /></Link></article>)}</div></div></section>

    <section className="section-edge bg-background"><div className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><div className="max-w-3xl"><p className="text-sm font-bold uppercase tracking-[0.16em] text-signal">Ocean document chain</p><h2 className="mt-3 text-3xl font-extrabold tracking-tight text-brand-deep sm:text-4xl">What belongs in an ocean shipment set?</h2></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["01", "Book & instruct", "Booking confirmation and shipping instructions."], ["02", "Check transport", "Draft/final B/L, vessel, voyage, ports and terms."], ["03", "Control equipment", "Container, seal, packages, weight, CBM and events."], ["04", "Manage arrival", "Arrival notice, free time, release and D&D evidence."]].map(([number, title, copy]) => <article key={number} className="rounded-2xl border border-amber/45 bg-white p-5"><span className="text-sm font-extrabold text-signal">{number}</span><h3 className="mt-3 font-extrabold text-brand-deep">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>

    <section className="mx-auto max-w-6xl px-4 py-16 sm:px-6 lg:py-24"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[Container, "Container number check", "Validate ISO 6346 numbers in bulk.", "/tools/container-number-check"], [Calculator, "LCL W/M calculator", "Audit CBM-versus-weight revenue tons.", "/tools/lcl-freight-calculator"], [TimerReset, "D&D calculator", "Audit free time and tiered daily charges.", "/tools/demurrage-detention-calculator"], [FileSearch, "Port code lookup", "Find maritime UN/LOCODE references.", "/tools/port-code-lookup"]].map(([Icon, title, copy, href]) => { const ToolIcon = Icon as typeof Calculator; return <Link key={String(title)} href={String(href)} className="group rounded-2xl border border-amber/45 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><div className="flex items-center justify-between"><ToolIcon className="size-6 text-signal" aria-hidden /><FreightModeTag mode="ocean" /></div><h2 className="mt-4 font-extrabold text-brand-deep">{String(title)}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{String(copy)}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-primary">Open <ArrowRight className="size-4" aria-hidden /></span></Link>; })}</div><div className="mt-8 flex items-start gap-3 rounded-2xl border border-primary/15 bg-secondary p-5"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-primary" aria-hidden /><p className="text-sm leading-6 text-muted-foreground"><strong className="text-primary">Clear boundary:</strong> GainingDocx checks paperwork consistency. It does not issue a B/L or delivery order, confirm cargo release, or replace carrier and terminal records.</p></div></section>
  </>;
}
