import type { Faq } from "@/lib/seo/jsonld";

export interface FeaturePage {
  slug: string;
  name: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  overview: string[];
  benefits: string[];
  workflow: string[];
  faqs: Faq[];
}

export const FEATURES: FeaturePage[] = [
  {
    slug: "shipping-document-data-extraction",
    name: "Shipping Document Data Extraction",
    metaTitle: "AI Shipping Document Data Extraction",
    description: "Extract parties, references, cargo lines, containers, ports, dates, weights and charges from shipping documents into structured data.",
    eyebrow: "AI extraction",
    overview: [
      "GainingDocx turns Bills of Lading, commercial invoices, packing lists and related shipment records into structured fields. It is designed for logistics documents rather than generic page text, so tables, cargo lines and maritime references stay connected to their meaning.",
      "The review screen keeps the source and extracted values together. Teams can correct uncertain fields before exporting them to Excel, CSV, JSON or a downstream workflow.",
    ],
    benefits: ["Document-specific fields and cargo lines", "Multi-page PDF and image support", "Human review before export", "Excel, CSV, JSON and PDF outputs"],
    workflow: ["Upload a PDF or page image.", "Review fields as they are extracted.", "Resolve warnings and export clean data."],
    faqs: [
      { q: "Which shipping documents can be extracted?", a: "The workspace supports Bills of Lading, sea waybills, commercial and freight invoices, packing lists, purchase orders, goods receipts, arrival notices and booking confirmations." },
      { q: "Can the result be corrected before export?", a: "Yes. Extracted values remain reviewable and editable so operational teams can confirm critical references before using the data." },
      { q: "Does it preserve line items?", a: "Yes. Where the source includes structured cargo or invoice rows, the parser returns line-level descriptions, quantities, weights, amounts and other available fields." },
    ],
  },
  {
    slug: "maritime-document-validation",
    name: "Maritime Document Validation",
    metaTitle: "Maritime Document Validation Checks",
    description: "Validate container numbers, IMO numbers, ports, dates, weights, package totals and financial arithmetic after document extraction.",
    eyebrow: "Deterministic validation",
    overview: [
      "OCR confidence alone cannot establish whether a shipping value is operationally valid. GainingDocx follows extraction with deterministic checks written in code, giving each issue a reproducible reason and expected value where one can be calculated.",
      "Checks include ISO 6346 container digits, IMO checksums, UN/LOCODE matching, date order, gross-versus-net weight, cargo totals and document-specific financial arithmetic.",
    ],
    benefits: ["Reproducible rule-based results", "Expected values for check-digit failures", "Warnings separated from blocking contradictions", "Clear review trail"],
    workflow: ["Extract the printed value.", "Run document-specific validation rules.", "Review pass, warning and fail results with explanations."],
    faqs: [
      { q: "Are validation results generated by AI?", a: "No. The AI reads the document; deterministic code performs checksum, arithmetic, date and reference checks." },
      { q: "Can validation prove that a document is genuine?", a: "No. It detects internal inconsistencies and invalid references, but it does not authenticate an issuer or replace carrier, customs or bank verification." },
      { q: "What happens when a check fails?", a: "The affected field is flagged with a plain-language explanation and, when calculable, the expected value." },
    ],
  },
  {
    slug: "shipment-document-matching",
    name: "Shipment Document Matching",
    metaTitle: "Shipment Document Matching & Discrepancy Checks",
    description: "Compare Bills of Lading, invoices, packing lists, purchase orders and goods receipts to find shipment discrepancies.",
    eyebrow: "Cross-document control",
    overview: [
      "Documents can be individually correct and still disagree with one another. Shipment Check groups related records and compares references, parties, routes, container numbers, quantities, weights, currency and totals across the document set.",
      "Differences become prioritized discrepancies so teams can focus on what may delay clearance, payment or delivery rather than manually comparing pages side by side.",
    ],
    benefits: ["Three-way PO, invoice and receipt matching", "B/L, invoice and packing-list comparison", "Red and amber discrepancy severity", "Shipment-level audit history"],
    workflow: ["Add documents to the same shipment.", "Run cross-document matching.", "Resolve or document each discrepancy."],
    faqs: [
      { q: "Which fields are compared?", a: "Available comparisons include document references, parties, ports, containers, quantities, weights, currencies, amounts and shipment dates." },
      { q: "Does matching overwrite source data?", a: "No. Matching reports agreements and differences while preserving the values extracted from each source document." },
      { q: "Can it support three-way matching?", a: "Yes. Purchase orders, commercial invoices and goods receipts can be linked and checked at header and line level when the necessary references are present." },
    ],
  },
  {
    slug: "shipping-document-search",
    name: "Shipping Document Search",
    metaTitle: "Shipping Document & Shipment Search",
    description: "Search shipping records by B/L, invoice, container, vessel, party, port or other extracted reference.",
    eyebrow: "Operational retrieval",
    overview: [
      "Shipping records are difficult to retrieve when the useful reference exists only inside a PDF. GainingDocx indexes the structured values already extracted from documents so operators can search the shipment context instead of filenames.",
      "Results connect documents to their shipment, review status and related records, shortening the path from a customer or carrier question to the supporting evidence.",
    ],
    benefits: ["Search by operational reference", "Find containers across documents", "Connect results to shipments", "Keep private account data isolated"],
    workflow: ["Parse and save a document.", "Search a known reference or party.", "Open the matching document or shipment."],
    faqs: [
      { q: "What can I search for?", a: "You can search common extracted values such as B/L and invoice numbers, containers, parties, vessels and ports." },
      { q: "Are my documents publicly searchable?", a: "No. Workspace search is private to the signed-in account and is not an internet search index." },
      { q: "Does search require exact filenames?", a: "No. Search uses structured document values, so the original filename does not need to contain the reference." },
    ],
  },
  {
    slug: "shipping-data-export",
    name: "Shipping Data Export",
    metaTitle: "Export Shipping Document Data to Excel, CSV & JSON",
    description: "Export reviewed shipping document fields and cargo lines to structured Excel, CSV, JSON and branded PDF reports.",
    eyebrow: "Ready-to-use outputs",
    overview: [
      "Parsed data becomes useful only when it can move into the next system. GainingDocx separates summary fields, containers and cargo lines into practical export structures for spreadsheets, audits and system integration.",
      "Exports are generated from the reviewed record rather than raw OCR text, preserving corrections and validation context made in the workspace.",
    ],
    benefits: ["Multi-sheet Excel workbooks", "Flat CSV for operational handoff", "Structured JSON for integrations", "Branded PDF review summaries"],
    workflow: ["Review the extracted document.", "Choose the required output format.", "Download and hand off the structured record."],
    faqs: [
      { q: "Which export formats are available?", a: "Reviewed documents can be exported as Excel, CSV, JSON and PDF, depending on the record and workflow." },
      { q: "Are line items included?", a: "Yes. Line-level cargo, invoice or container data is included when it was available in the parsed source." },
      { q: "Do exports include my corrections?", a: "Yes. Exports are generated from the current reviewed record, including saved field corrections." },
    ],
  },
  {
    slug: "shipping-document-generation",
    name: "Shipping Document Generation",
    metaTitle: "Generate Shipping Documents from Reviewed Data",
    description: "Reuse reviewed shipment data to prepare editable packing lists, commercial invoices and shipping-instruction drafts.",
    eyebrow: "Document reuse",
    overview: [
      "The same shipment facts are often typed repeatedly into related documents. GainingDocx maps reviewed source data into an editable counterpart-document draft so teams can reuse party, routing and cargo details without starting from a blank form.",
      "Generated documents remain drafts for human review. Users can adjust document-specific declarations and fields before downloading or sending them into the formal issuance process.",
    ],
    benefits: ["Reuse reviewed shipment facts", "Editable before download", "Document-specific field mapping", "Clear draft status and authority notices"],
    workflow: ["Open a reviewed source document.", "Choose a compatible document type.", "Review the mapped draft and download it."],
    faqs: [
      { q: "Does generation issue an official Bill of Lading?", a: "No. Only a carrier, NVOCC or authorized agent can issue the transport document. Generated materials are working drafts or data worksheets." },
      { q: "Can I edit the generated document?", a: "Yes. Mapped values can be reviewed and adjusted before download." },
      { q: "Which documents can be generated?", a: "Available mappings include practical drafts such as packing lists, commercial invoices and shipping instructions, depending on the source data." },
    ],
  },
  {
    slug: "air-freight-document-automation",
    name: "Air Freight Document Automation",
    metaTitle: "Air Freight Document Processing & AWB Automation",
    description: "Extract and connect AWBs, air SLIs, manifests, commercial documents, security declarations and dangerous-goods paperwork.",
    eyebrow: "Air cargo operations",
    overview: [
      "GainingDocx treats air cargo as a complete paperwork chain rather than a single AWB upload. Email or upload the Shipper's Letter of Instruction, MAWB or HAWB, commercial invoice, packing list, manifest and related declarations into one shipment workspace.",
      "Air-specific validation checks airport-code format, AWB number arithmetic, prefix consistency, piece and weight totals, while source-linked review keeps operators in control of every correction.",
    ],
    benefits: ["MAWB and HAWB-aware extraction", "Airports, pieces and chargeable-weight checks", "Email-in or manual batch intake", "Source-linked human review"],
    workflow: ["Forward or upload the complete air document set.", "Review extracted parties, route, cargo, weights and special handling.", "Resolve prioritized findings and export the corrected data."],
    faqs: [
      { q: "Which air cargo documents are supported?", a: "Air Waybills, air Shipper's Letters of Instruction, Dangerous Goods Declarations, air cargo manifests, Cargo Security Declarations, commercial invoices, packing lists, rate documents and freight invoices are supported." },
      { q: "Does this issue an official e-AWB?", a: "No. It prepares, extracts and checks document data. The airline, authorized agent or connected cargo system remains responsible for formal issuance and transmission." },
      { q: "Can exporters use it without air-cargo expertise?", a: "Yes. The Air Freight workspace asks what you are trying to complete and presents the required document set in plain language." },
    ],
  },
  {
    slug: "mawb-hawb-reconciliation",
    name: "MAWB–HAWB Reconciliation",
    metaTitle: "MAWB HAWB Reconciliation & Air Consolidation Check",
    description: "Match house air waybills to the master route, parent reference, manifest, pieces and weight totals.",
    eyebrow: "Air consolidation control",
    overview: [
      "Air consolidations fail when house-level data drifts from the airline master record or manifest. GainingDocx identifies explicitly labelled master and house waybills, then compares parent references and route evidence.",
      "House piece, gross-weight and chargeable-weight totals are aggregated against the MAWB so an operator can focus immediately on the non-reconciling record.",
    ],
    benefits: ["Parent MAWB reference check", "Origin and destination consistency", "Aggregated house totals", "Manifest-to-master comparison"],
    workflow: ["Add the MAWB, all HAWBs and the manifest.", "Run the air consolidation workflow.", "Review missing houses, route differences and non-reconciling totals."],
    faqs: [
      { q: "How does the system distinguish a MAWB from a HAWB?", a: "It uses explicit labels and printed parent references. It does not guess the level solely from number format." },
      { q: "Can multiple HAWBs be checked together?", a: "Yes. Their printed piece, gross-weight and chargeable-weight totals are aggregated and compared with the master evidence." },
    ],
  },
  {
    slug: "airfreight-invoice-audit",
    name: "Airfreight Invoice Audit",
    metaTitle: "Airfreight Invoice Audit & Chargeable Weight Check",
    description: "Compare airfreight quotations and invoices against AWB references, route, chargeable weight and individual charge lines.",
    eyebrow: "Air cargo cost control",
    overview: [
      "Airfreight cost leakage often begins with the wrong chargeable weight, an unexpected surcharge or a rate applied to the wrong lane. GainingDocx connects the quotation, AWB and freight invoice instead of checking only the final total.",
      "The audit flags unsupported charges, duplicate charge lines, currency differences, route conflicts and kilogram billing quantities that do not match the AWB chargeable weight.",
    ],
    benefits: ["AWB-to-invoice reference matching", "Chargeable-weight billing check", "Duplicate and unsupported charge detection", "Questioned-amount reporting"],
    workflow: ["Add the rate or quotation, AWB and invoice.", "Run the airfreight invoice audit.", "Review questioned charges and export the evidence."],
    faqs: [
      { q: "Does the audit know my private contracted rate?", a: "Only when you provide the quotation or rate agreement. GainingDocx does not invent or scrape private rates." },
      { q: "Can it calculate volumetric weight?", a: "Yes. Use the free chargeable-weight calculator, then compare the verified result to the extracted AWB and invoice basis." },
    ],
  },
  {
    slug: "air-dangerous-goods-readiness",
    name: "Air Dangerous Goods Readiness",
    metaTitle: "Air Dangerous Goods Document Pre-Check",
    description: "Pre-check DGD, AWB and SLI data for missing or conflicting UN, class, packing, route and signature evidence.",
    eyebrow: "Qualified-review support",
    overview: [
      "Dangerous-goods paperwork requires specialist review. GainingDocx helps the qualified operator by extracting declaration evidence consistently and showing missing or conflicting values before acceptance review begins.",
      "The workflow compares AWB references, shipper, airports, UN numbers, proper shipping names, hazard classes and packing groups across the DGD and AWB. It clearly stops short of issuing a regulatory compliance certificate.",
    ],
    benefits: ["DGD signature and date presence", "UN and hazard-class structure checks", "DGD-to-AWB consistency", "Cargo Aircraft Only and forbidden indicators"],
    workflow: ["Add the DGD, AWB and air SLI.", "Review extracted dangerous-goods and aircraft-limitation evidence.", "Send every finding to a qualified dangerous-goods specialist for final acceptance."],
    faqs: [
      { q: "Is this an IATA DGR compliance certificate?", a: "No. It is a document pre-check that supports qualified review and does not replace the current IATA DGR, carrier variations or trained acceptance personnel." },
      { q: "What happens when a document says the item is forbidden?", a: "The workflow raises a stop-level finding and directs the user to qualified dangerous-goods review." },
    ],
  },
  {
    slug: "email-in-document-ingestion",
    name: "Email-In Document Ingestion",
    metaTitle: "Email-In Freight Document Processing",
    description: "Forward freight documents to a private GainingDocx address and receive the completed shipment check by reply email.",
    eyebrow: "Zero-upload intake",
    overview: [
      "Freight documents already arrive through email, so downloading every attachment and uploading it into another portal adds avoidable handling. Each signed-in GainingDocx account receives a private intake address for forwarding PDFs and document images directly into its workspace.",
      "Supported attachments are saved, extracted and grouped into shipment records. The sender receives a reply with secure workspace links, plus a generated discrepancy PDF when connected documents produce cross-document findings. Manual batch upload remains available alongside email-in.",
    ],
    benefits: ["Private, rotatable intake address", "File-signature and abuse checks before processing", "Automatic workspace and shipment creation", "Live status plus result reply to the sender"],
    workflow: ["Forward the shipment email with its attachments.", "GainingDocx extracts, groups and checks the supported documents.", "Open the result from the reply email or workspace."],
    faqs: [
      { q: "Which email attachments are supported?", a: "Email-in accepts PDF, JPG, PNG and WebP attachments. One message can contain up to 20 attachments and must remain within the 25 MiB email intake limit." },
      { q: "Is this a second email inbox?", a: "No. It is a unique routing alias. You keep using Gmail, Outlook or your operations mailbox; forwarding to the alias places supported attachments directly into your signed-in GainingDocx workspace." },
      { q: "Is the email-in address private?", a: "It is a private, account-specific intake address. Anyone who has it can add supported documents to that workspace, so it should be shared only with the intended forwarding team and rotated if exposed." },
      { q: "Why use email instead of requiring an API?", a: "Email works immediately with the channel freight teams and their partners already use. Manual upload remains available, while API and TMS connections are better suited to higher-volume structured integrations." },
      { q: "Does email-in replace manual upload?", a: "No. Email-in removes repeat downloading and uploading for inbox-based work, while manual single-document and batch upload remain available." },
      { q: "Does the reply guarantee every extracted value is correct?", a: "No. Automated extraction and checks support review; important operational values should still be verified against the attached source documents." },
    ],
  },
];
