import type { Faq } from "@/lib/seo/jsonld";

export interface FeaturePage {
  slug: string;
  name: string;
  metaTitle: string;
  description: string;
  eyebrow: string;
  overview: string[];
  benefits: string[];
  workflow: string[];
  faqs: Faq[];
}

export const FEATURES: FeaturePage[] = [
  {
    slug: "shipping-document-data-extraction",
    name: "Shipping Document Data Extraction",
    metaTitle: "AI Shipping Document Data Extraction",
    description: "Extract parties, references, cargo lines, containers, ports, dates, weights and charges from shipping documents into structured data.",
    eyebrow: "AI extraction",
    overview: [
      "GainingDocx turns Bills of Lading, commercial invoices, packing lists and related shipment records into structured fields. It is designed for logistics documents rather than generic page text, so tables, cargo lines and maritime references stay connected to their meaning.",
      "The review screen keeps the source and extracted values together. Teams can correct uncertain fields before exporting them to Excel, CSV, JSON or a downstream workflow.",
    ],
    benefits: ["Document-specific fields and cargo lines", "Multi-page PDF and image support", "Human review before export", "Excel, CSV, JSON and PDF outputs"],
    workflow: ["Upload a PDF or page image.", "Review fields as they are extracted.", "Resolve warnings and export clean data."],
    faqs: [
      { q: "Which shipping documents can be extracted?", a: "The workspace supports Bills of Lading, sea waybills, commercial and freight invoices, packing lists, purchase orders, goods receipts, arrival notices and booking confirmations." },
      { q: "Can the result be corrected before export?", a: "Yes. Extracted values remain reviewable and editable so operational teams can confirm critical references before using the data." },
      { q: "Does it preserve line items?", a: "Yes. Where the source includes structured cargo or invoice rows, the parser returns line-level descriptions, quantities, weights, amounts and other available fields." },
    ],
  },
  {
    slug: "maritime-document-validation",
    name: "Maritime Document Validation",
    metaTitle: "Maritime Document Validation Checks",
    description: "Validate container numbers, IMO numbers, ports, dates, weights, package totals and financial arithmetic after document extraction.",
    eyebrow: "Deterministic validation",
    overview: [
      "OCR confidence alone cannot establish whether a shipping value is operationally valid. GainingDocx follows extraction with deterministic checks written in code, giving each issue a reproducible reason and expected value where one can be calculated.",
      "Checks include ISO 6346 container digits, IMO checksums, UN/LOCODE matching, date order, gross-versus-net weight, cargo totals and document-specific financial arithmetic.",
    ],
    benefits: ["Reproducible rule-based results", "Expected values for check-digit failures", "Warnings separated from blocking contradictions", "Clear review trail"],
    workflow: ["Extract the printed value.", "Run document-specific validation rules.", "Review pass, warning and fail results with explanations."],
    faqs: [
      { q: "Are validation results generated by AI?", a: "No. The AI reads the document; deterministic code performs checksum, arithmetic, date and reference checks." },
      { q: "Can validation prove that a document is genuine?", a: "No. It detects internal inconsistencies and invalid references, but it does not authenticate an issuer or replace carrier, customs or bank verification." },
      { q: "What happens when a check fails?", a: "The affected field is flagged with a plain-language explanation and, when calculable, the expected value." },
    ],
  },
  {
    slug: "shipment-document-matching",
    name: "Shipment Document Matching",
    metaTitle: "Shipment Document Matching & Discrepancy Checks",
    description: "Compare Bills of Lading, invoices, packing lists, purchase orders and goods receipts to find shipment discrepancies.",
    eyebrow: "Cross-document control",
    overview: [
      "Documents can be individually correct and still disagree with one another. Shipment Check groups related records and compares references, parties, routes, container numbers, quantities, weights, currency and totals across the document set.",
      "Differences become prioritized discrepancies so teams can focus on what may delay clearance, payment or delivery rather than manually comparing pages side by side.",
    ],
    benefits: ["Three-way PO, invoice and receipt matching", "B/L, invoice and packing-list comparison", "Red and amber discrepancy severity", "Shipment-level audit history"],
    workflow: ["Add documents to the same shipment.", "Run cross-document matching.", "Resolve or document each discrepancy."],
    faqs: [
      { q: "Which fields are compared?", a: "Available comparisons include document references, parties, ports, containers, quantities, weights, currencies, amounts and shipment dates." },
      { q: "Does matching overwrite source data?", a: "No. Matching reports agreements and differences while preserving the values extracted from each source document." },
      { q: "Can it support three-way matching?", a: "Yes. Purchase orders, commercial invoices and goods receipts can be linked and checked at header and line level when the necessary references are present." },
    ],
  },
  {
    slug: "shipping-document-search",
    name: "Shipping Document Search",
    metaTitle: "Shipping Document & Shipment Search",
    description: "Search shipping records by B/L, invoice, container, vessel, party, port or other extracted reference.",
    eyebrow: "Operational retrieval",
    overview: [
      "Shipping records are difficult to retrieve when the useful reference exists only inside a PDF. GainingDocx indexes the structured values already extracted from documents so operators can search the shipment context instead of filenames.",
      "Results connect documents to their shipment, review status and related records, shortening the path from a customer or carrier question to the supporting evidence.",
    ],
    benefits: ["Search by operational reference", "Find containers across documents", "Connect results to shipments", "Keep private account data isolated"],
    workflow: ["Parse and save a document.", "Search a known reference or party.", "Open the matching document or shipment."],
    faqs: [
      { q: "What can I search for?", a: "You can search common extracted values such as B/L and invoice numbers, containers, parties, vessels and ports." },
      { q: "Are my documents publicly searchable?", a: "No. Workspace search is private to the signed-in account and is not an internet search index." },
      { q: "Does search require exact filenames?", a: "No. Search uses structured document values, so the original filename does not need to contain the reference." },
    ],
  },
  {
    slug: "shipping-data-export",
    name: "Shipping Data Export",
    metaTitle: "Export Shipping Document Data to Excel, CSV & JSON",
    description: "Export reviewed shipping document fields and cargo lines to structured Excel, CSV, JSON and branded PDF reports.",
    eyebrow: "Ready-to-use outputs",
    overview: [
      "Parsed data becomes useful only when it can move into the next system. GainingDocx separates summary fields, containers and cargo lines into practical export structures for spreadsheets, audits and system integration.",
      "Exports are generated from the reviewed record rather than raw OCR text, preserving corrections and validation context made in the workspace.",
    ],
    benefits: ["Multi-sheet Excel workbooks", "Flat CSV for operational handoff", "Structured JSON for integrations", "Branded PDF review summaries"],
    workflow: ["Review the extracted document.", "Choose the required output format.", "Download and hand off the structured record."],
    faqs: [
      { q: "Which export formats are available?", a: "Reviewed documents can be exported as Excel, CSV, JSON and PDF, depending on the record and workflow." },
      { q: "Are line items included?", a: "Yes. Line-level cargo, invoice or container data is included when it was available in the parsed source." },
      { q: "Do exports include my corrections?", a: "Yes. Exports are generated from the current reviewed record, including saved field corrections." },
    ],
  },
  {
    slug: "shipping-document-generation",
    name: "Shipping Document Generation",
    metaTitle: "Generate Shipping Documents from Reviewed Data",
    description: "Reuse reviewed shipment data to prepare editable packing lists, commercial invoices and shipping-instruction drafts.",
    eyebrow: "Document reuse",
    overview: [
      "The same shipment facts are often typed repeatedly into related documents. GainingDocx maps reviewed source data into an editable counterpart-document draft so teams can reuse party, routing and cargo details without starting from a blank form.",
      "Generated documents remain drafts for human review. Users can adjust document-specific declarations and fields before downloading or sending them into the formal issuance process.",
    ],
    benefits: ["Reuse reviewed shipment facts", "Editable before download", "Document-specific field mapping", "Clear draft status and authority notices"],
    workflow: ["Open a reviewed source document.", "Choose a compatible document type.", "Review the mapped draft and download it."],
    faqs: [
      { q: "Does generation issue an official Bill of Lading?", a: "No. Only a carrier, NVOCC or authorized agent can issue the transport document. Generated materials are working drafts or data worksheets." },
      { q: "Can I edit the generated document?", a: "Yes. Mapped values can be reviewed and adjusted before download." },
      { q: "Which documents can be generated?", a: "Available mappings include practical drafts such as packing lists, commercial invoices and shipping instructions, depending on the source data." },
    ],
  },
];
