export const TOOLS = [
  { slug: "cbm-calculator", name: "CBM Calculator", description: "Calculate and export multi-line shipment volume and weight in mm, cm, m or inches.", intro: "Add every carton-size group in the shipment. The calculator converts each row to cubic metres, multiplies by quantity, sums gross weight and exports an auditable CSV calculation." },
  { slug: "container-load-calculator", name: "Container Carton Fit Calculator", description: "Check identical-carton stowage by internal dimensions, rotation and payload.", intro: "Test an identical carton group against approximate internal dimensions and payload for 20GP, 40GP, 40HC or 45HC equipment. The tool checks six orthogonal rotations, spatial count and weight count; mixed-SKU and operational loading still require a detailed stow plan." },
  { slug: "container-number-check", name: "Container Number Check", description: "Batch-validate up to 100 ISO 6346 container numbers and export results.", intro: "Paste full container numbers. The deterministic ISO 6346 calculation checks owner prefix, equipment category, serial and check digit, proposes the expected full number and exports a CSV audit." },
  { slug: "port-code-lookup", name: "UN/LOCODE Port Lookup", description: "Find maritime location codes by port name or five-character code.", intro: "Search the bundled UNECE UN/LOCODE port dataset. Results show the two-letter country prefix plus three-character location code." },
  { slug: "chargeable-weight-calculator", name: "Chargeable Weight Calculator", description: "Calculate multiple package groups using express, air-cargo or custom divisors.", intro: "Enter each package group separately, choose the tariff basis and compare summed volumetric weight with total actual weight. Express 5,000 cm³/kg, general air cargo 6,000 cm³/kg and 139 in³/lb modes are kept distinct to prevent under-rating." },
  { slug: "lcl-freight-calculator", name: "LCL Freight W/M Calculator", description: "Audit LCL ocean freight using CBM-versus-weight revenue tons and accessorial charges.", intro: "Enter the shipment CBM and gross weight from the B/L or packing list, then the quoted W/M rate and charges. The calculator identifies whether measurement or weight controls and produces an auditable freight estimate for invoice checking." },
  { slug: "demurrage-detention-calculator", name: "Demurrage & Detention Calculator", description: "Audit free time, tiered daily charges and fixed fees from arrival or equipment-return dates.", intro: "Enter the contractual start and end dates, free days, rate tiers and fixed charges. The calculator shows elapsed, free and chargeable days separately so an arrival notice or carrier invoice can be checked without hidden date arithmetic." },
  { slug: "hs-code-finder", name: "HS Code Finder & U.S. Tariff Lookup", description: "Search official U.S. HTS descriptions, identify the international 6-digit HS heading and review published duty-rate fields.", intro: "Describe a commodity to search the official U.S. International Trade Commission tariff schedule. Results separate the international six-digit HS code from the longer U.S. HTS classification and show published rate fields where available." },
  { slug: "shipping-mark-generator", name: "Shipping Mark Generator", description: "Create a clean, printable carton shipping mark without an account.", intro: "Enter consignee, destination, purchase order, case range, weights and handling instructions. Preview the mark immediately, then print it, save it as PDF or download an editable HTML copy." },
] as const;
