// PDF primitives + the branded Summary Report one-pager (BUILD_SPEC §M7).
// pdf-lib only (works on Workers, no font embedding needed for Helvetica).

import {
  PDFDocument,
  PDFFont,
  PDFImage,
  PDFPage,
  StandardFonts,
  degrees,
  rgb,
  type RGB,
} from "pdf-lib";

import { LOGO_PNG_BASE64 } from "@/lib/brand/logo-data";
import type { ValidationResult } from "@/lib/validators";
import { containerRows, docRef, summaryPairs } from "./rows";

export const NAVY = rgb(0.004, 0.231, 0.702); // logo blue #013BB3
export const ORANGE = rgb(0.831, 0.02, 0.02); // logo red #D40505
export const GREEN = rgb(0.004, 0.231, 0.702);
export const AMBER = rgb(0.831, 0.02, 0.02);
export const RED = rgb(0.831, 0.02, 0.02);
export const GRAY = rgb(0.294, 0.396, 0.576);
export const LIGHT = rgb(0.91, 0.941, 1);

export const A4: [number, number] = [595.28, 841.89];
export const MARGIN = 48;

export interface Fonts {
  regular: PDFFont;
  bold: PDFFont;
}

export async function newDoc(): Promise<{
  pdf: PDFDocument;
  fonts: Fonts;
  logo: PDFImage;
}> {
  const pdf = await PDFDocument.create();
  pdf.setProducer("GainingDocx");
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const logo = await pdf.embedPng(Uint8Array.from(atob(LOGO_PNG_BASE64), (c) => c.charCodeAt(0)));
  return { pdf, fonts: { regular, bold }, logo };
}

/** Helvetica is WinAnsi-only — replace unencodable characters. */
export function enc(text: string): string {
  let out = "";
  for (const ch of text.normalize("NFC")) {
    const c = ch.codePointAt(0)!;
    out +=
      (c >= 0x20 && c <= 0xff) || c === 0x2026 || c === 0x2014 || c === 0x2022
        ? ch
        : "?";
  }
  return out;
}

export function truncate(font: PDFFont, text: string, size: number, maxWidth: number): string {
  let t = enc(text);
  if (font.widthOfTextAtSize(t, size) <= maxWidth) return t;
  while (t.length > 1 && font.widthOfTextAtSize(t + "…", size) > maxWidth) {
    t = t.slice(0, -1);
  }
  return t + "…";
}

/** Navy brand band with logo, product name, doc title and reference. */
export function drawHeader(
  page: PDFPage,
  fonts: Fonts,
  title: string,
  ref: string | null,
  logo?: PDFImage
) {
  const [w, h] = [page.getWidth(), page.getHeight()];
  page.drawRectangle({ x: 0, y: h - 92, width: w, height: 92, color: NAVY });
  page.drawRectangle({ x: 0, y: h - 96, width: w, height: 4, color: ORANGE });
  let tx = MARGIN;
  if (logo) {
    page.drawImage(logo, { x: MARGIN, y: h - 78, width: 56, height: 56 });
    tx = MARGIN + 68;
  }
  page.drawText("GainingDocx", {
    x: tx, y: h - 40, size: 16, font: fonts.bold, color: rgb(1, 1, 1),
  });
  page.drawText(title, {
    x: tx, y: h - 68, size: 12, font: fonts.regular, color: rgb(0.85, 0.88, 0.92),
  });
  if (ref) {
    const size = 14;
    const safe = enc(ref);
    const width = fonts.bold.widthOfTextAtSize(safe, size);
    page.drawText(safe, {
      x: w - MARGIN - width, y: h - 46, size, font: fonts.bold, color: rgb(1, 1, 1),
    });
  }
}

export function drawFooter(page: PDFPage, fonts: Fonts, note?: string) {
  page.drawText(
    `Generated by GainingDocx · gainingdocx.com · ${new Date().toISOString().slice(0, 10)}`,
    { x: MARGIN, y: 30, size: 8, font: fonts.regular, color: GRAY }
  );
  if (note) {
    page.drawText(truncate(fonts.regular, note, 8, page.getWidth() - 2 * MARGIN), {
      x: MARGIN, y: 42, size: 8, font: fonts.regular, color: GRAY,
    });
  }
}

/** Free-plan watermark (spec §M7): faint centered logo + diagonal text. */
export function drawWatermark(page: PDFPage, fonts: Fonts, logo?: PDFImage) {
  if (logo) {
    const size = 340;
    page.drawImage(logo, {
      x: (page.getWidth() - size) / 2,
      y: (page.getHeight() - size) / 2 - 40,
      width: size,
      height: size,
      opacity: 0.06,
    });
  }
  page.drawText("GainingDocx FREE", {
    x: 90,
    y: 240,
    size: 58,
    font: fonts.bold,
    color: rgb(0.85, 0.86, 0.88),
    opacity: 0.35,
    rotate: degrees(35),
  });
}

const TYPE_TITLE: Record<string, string> = {
  bill_of_lading: "Bill of Lading — parsed summary",
  sea_waybill: "Sea Waybill — parsed summary",
  commercial_invoice: "Commercial Invoice — parsed summary",
  purchase_order: "Purchase Order — parsed summary",
  freight_invoice: "Freight Invoice — parsed summary",
  goods_receipt: "Goods Receipt — parsed summary",
  packing_list: "Packing List — parsed summary",
  arrival_notice: "Arrival Notice — parsed summary",
  booking_confirmation: "Booking Confirmation — parsed summary",
  air_waybill: "Air Waybill — parsed summary",
  other: "Shipping document — parsed summary",
};

/** Branded one-pager: key fields, validation badge strip, containers. */
export async function summaryReportPdf(opts: {
  docType: string;
  fields: Record<string, unknown>;
  validation: ValidationResult[];
  shareUrl: string | null;
}): Promise<Uint8Array> {
  const { pdf, fonts, logo } = await newDoc();
  const page = pdf.addPage(A4);
  const w = page.getWidth();
  drawHeader(page, fonts, TYPE_TITLE[opts.docType] ?? TYPE_TITLE.other, docRef(opts.fields), logo);

  let y = page.getHeight() - 130;

  // Validation badge strip.
  const counts = { pass: 0, warn: 0, fail: 0 };
  for (const v of opts.validation) counts[v.status] += 1;
  const badges: [string, number, RGB][] = [
    ["PASS", counts.pass, GREEN],
    ["WARN", counts.warn, AMBER],
    ["FAIL", counts.fail, RED],
  ];
  let bx = MARGIN;
  for (const [label, count, color] of badges) {
    page.drawRectangle({ x: bx, y: y - 6, width: 86, height: 24, color, opacity: 0.12 });
    page.drawRectangle({ x: bx, y: y - 6, width: 3, height: 24, color });
    page.drawText(`${count} ${label}`, {
      x: bx + 10, y: y, size: 10, font: fonts.bold, color,
    });
    bx += 96;
  }
  page.drawText(
    opts.validation.length === 0
      ? "No deterministic checks ran"
      : counts.fail > 0
        ? "Verify the failed fields against the original document"
        : "Deterministic checks look consistent",
    { x: bx + 8, y, size: 9, font: fonts.regular, color: GRAY }
  );
  y -= 34;

  // Flagged messages (up to 4).
  for (const v of opts.validation.filter((x) => x.status !== "pass").slice(0, 4)) {
    page.drawText(truncate(fonts.regular, `• [${v.status.toUpperCase()}] ${v.message}`, 8.5, w - 2 * MARGIN), {
      x: MARGIN, y, size: 8.5, font: fonts.regular,
      color: v.status === "fail" ? RED : AMBER,
    });
    y -= 13;
  }
  y -= 10;

  // Key fields, two-column grid.
  const pairs = summaryPairs(opts.docType, opts.fields).filter((p) => p.value !== "");
  const colW = (w - 2 * MARGIN) / 2;
  const rows = Math.ceil(Math.min(pairs.length, 22) / 2);
  for (let i = 0; i < Math.min(pairs.length, 22); i++) {
    const col = Math.floor(i / rows);
    const x = MARGIN + col * colW;
    const yy = y - (i % rows) * 30;
    page.drawText(pairs[i].label.toUpperCase(), {
      x, y: yy, size: 7, font: fonts.regular, color: GRAY,
    });
    page.drawText(truncate(fonts.bold, pairs[i].value, 10, colW - 16), {
      x, y: yy - 11, size: 10, font: fonts.bold, color: NAVY,
    });
  }
  y -= rows * 30 + 16;

  // Containers table (B/L).
  const containers = containerRows(opts.fields);
  if (containers.length > 0 && y > 120) {
    page.drawText("CONTAINERS", { x: MARGIN, y, size: 8, font: fonts.bold, color: GRAY });
    y -= 14;
    const cols = [0, 1, 2, 3, 5] as const; // no, seal, type, packages, gross
    const widths = [120, 90, 60, 70, 90];
    page.drawRectangle({ x: MARGIN, y: y - 4, width: w - 2 * MARGIN, height: 16, color: LIGHT });
    let cx = MARGIN + 4;
    const headerNames = ["Container", "Seal", "Type", "Packages", "Gross kg"];
    headerNames.forEach((name, ci) => {
      page.drawText(name, { x: cx, y, size: 8, font: fonts.bold, color: NAVY });
      cx += widths[ci];
    });
    y -= 16;
    for (const row of containers.slice(1, 9)) {
      let x = MARGIN + 4;
      cols.forEach((c, ci) => {
        page.drawText(truncate(fonts.regular, String(row[c] ?? ""), 8.5, widths[ci] - 8), {
          x, y, size: 8.5, font: fonts.regular, color: NAVY,
        });
        x += widths[ci];
      });
      y -= 14;
    }
  }

  drawFooter(
    page,
    fonts,
    opts.shareUrl ? `Live read-only copy: ${opts.shareUrl}` : undefined
  );
  return pdf.save();
}
