// PDF renderer for generated drafts (BUILD_SPEC §M7). One layout serves
// packing list, commercial invoice and shipping instructions — columns are
// shown only when the draft carries data for them. Watermark on free plan.

import {
  A4,
  GRAY,
  LIGHT,
  MARGIN,
  NAVY,
  drawFooter,
  drawWatermark,
  newDoc,
  truncate,
  type Fonts,
} from "@/lib/export/pdf";
import { rgb, type PDFImage, type PDFPage } from "pdf-lib";

import type { GenDoc, GenLine } from "./map";

const COLS: { key: keyof GenLine; label: string; width: number }[] = [
  { key: "description", label: "Description", width: 150 },
  { key: "hs_code", label: "HS code", width: 52 },
  { key: "packages", label: "Pkgs", width: 36 },
  { key: "cartons", label: "Cartons", width: 44 },
  { key: "net_kg", label: "Net kg", width: 46 },
  { key: "gross_kg", label: "Gross kg", width: 50 },
  { key: "volume_cbm", label: "CBM", width: 38 },
  { key: "unit_price", label: "Unit", width: 40 },
  { key: "amount", label: "Amount", width: 50 },
];

function drawTitle(page: PDFPage, fonts: Fonts, title: string, logo?: PDFImage) {
  const w = page.getWidth();
  const h = page.getHeight();
  page.drawRectangle({ x: 0, y: h - 70, width: w, height: 70, color: NAVY });
  let tx = MARGIN;
  if (logo) {
    page.drawImage(logo, { x: MARGIN, y: h - 61, width: 52, height: 52 });
    tx = MARGIN + 64;
  }
  page.drawText(title, {
    x: tx, y: h - 44, size: 16, font: fonts.bold, color: rgb(1, 1, 1),
  });
  page.drawText("Draft generated by GainingDocx — review before use", {
    x: tx, y: h - 60, size: 8, font: fonts.regular, color: rgb(0.8, 0.84, 0.9),
  });
}

export async function generatedDocPdf(
  gen: GenDoc,
  watermark: boolean
): Promise<Uint8Array> {
  const { pdf, fonts, logo } = await newDoc();
  let page = pdf.addPage(A4);
  const w = page.getWidth();
  if (watermark) drawWatermark(page, fonts, logo);
  drawTitle(page, fonts, gen.title, logo);

  let y = page.getHeight() - 100;

  const continuation = () => {
    page = pdf.addPage(A4);
    if (watermark) drawWatermark(page, fonts, logo);
    drawTitle(page, fonts, `${gen.title} — CONTINUED`, logo);
    y = page.getHeight() - 100;
  };

  const wrap = (text: string, maxWidth: number, size: number) => {
    const out: string[] = [];
    for (const paragraph of text.replace(/\r/g, "").split("\n")) {
      const words = paragraph.split(/\s+/).filter(Boolean);
      if (words.length === 0) { out.push(""); continue; }
      let row = "";
      for (const word of words) {
        const next = row ? `${row} ${word}` : word;
        if (fonts.regular.widthOfTextAtSize(next, size) <= maxWidth) row = next;
        else { if (row) out.push(row); row = word; }
      }
      if (row) out.push(row);
    }
    return out;
  };

  // Header facts in two columns.
  const facts = gen.header.filter((f) => f.value.trim() !== "");
  const colW = (w - 2 * MARGIN) / 2;
  const factRows = Math.ceil(facts.length / 2);
  facts.forEach((f, i) => {
    const x = MARGIN + Math.floor(i / factRows) * colW;
    const yy = y - (i % factRows) * 26;
    page.drawText(f.label.toUpperCase(), { x, y: yy, size: 7, font: fonts.regular, color: GRAY });
    page.drawText(truncate(fonts.bold, f.value, 10, colW - 16), {
      x, y: yy - 10, size: 10, font: fonts.bold, color: NAVY,
    });
  });
  y -= factRows * 26 + 18;

  // Party blocks side by side.
  const parties = gen.parties.filter((p) => p.value.trim() !== "");
  if (parties.length > 0) {
    const pw = (w - 2 * MARGIN - (parties.length - 1) * 12) / parties.length;
    let maxLines = 0;
    parties.forEach((p, pi) => {
      const x = MARGIN + pi * (pw + 12);
      page.drawText(p.label.toUpperCase(), { x, y, size: 7, font: fonts.regular, color: GRAY });
      const lines = p.value.split("\n").slice(0, 5);
      maxLines = Math.max(maxLines, lines.length);
      lines.forEach((line, li) => {
        page.drawText(truncate(fonts.regular, line, 9, pw - 8), {
          x, y: y - 12 - li * 12, size: 9, font: fonts.regular, color: NAVY,
        });
      });
    });
    y -= 12 + maxLines * 12 + 18;
  }

  // Lines table: only columns that carry data anywhere.
  const active = COLS.filter(
    (c) => c.key === "description" || gen.lines.some((l) => l[c.key].trim() !== "")
  );
  const totalW = active.reduce((a, c) => a + c.width, 0);
  const scale = (w - 2 * MARGIN) / totalW;
  if (gen.lines.length > 0) {
    const tableHeader = () => {
      page.drawRectangle({ x: MARGIN, y: y - 4, width: w - 2 * MARGIN, height: 16, color: LIGHT });
      let x = MARGIN + 3;
      for (const c of active) {
        page.drawText(c.label, { x, y, size: 8, font: fonts.bold, color: NAVY });
        x += c.width * scale;
      }
      y -= 16;
    };
    tableHeader();
    for (const line of gen.lines) {
      if (y < 90) { continuation(); tableHeader(); }
      let lx = MARGIN + 3;
      for (const c of active) {
        page.drawText(truncate(fonts.regular, line[c.key], 8.5, c.width * scale - 6), {
          x: lx, y, size: 8.5, font: fonts.regular, color: NAVY,
        });
        lx += c.width * scale;
      }
      y -= 14;
    }
    y -= 8;
  }

  // Totals, right-aligned block.
  const totals = gen.totals.filter((t) => t.value.trim() !== "");
  if (y - totals.length * 15 < 75) continuation();
  for (const t of totals) {
    const label = `${t.label}:`;
    const lw = fonts.regular.widthOfTextAtSize(label, 9);
    const vw = fonts.bold.widthOfTextAtSize(t.value, 10);
    page.drawText(label, {
      x: w - MARGIN - 115 - lw,
      y,
      size: 9,
      font: fonts.regular,
      color: GRAY,
    });
    page.drawText(truncate(fonts.bold, t.value, 10, 100), {
      x: w - MARGIN - vw, y, size: 10, font: fonts.bold, color: NAVY,
    });
    y -= 15;
  }
  y -= 10;

  // Notes.
  if (gen.notes.trim() !== "") {
    if (y < 90) continuation();
    page.drawText("NOTES", { x: MARGIN, y, size: 7, font: fonts.regular, color: GRAY });
    y -= 12;
    for (const line of wrap(gen.notes, w - 2 * MARGIN, 8.5)) {
      if (y < 55) { continuation(); page.drawText("NOTES — CONTINUED", { x: MARGIN, y, size: 7, font: fonts.regular, color: GRAY }); y -= 12; }
      page.drawText(line, {
        x: MARGIN, y, size: 8.5, font: fonts.regular, color: NAVY,
      });
      y -= 12;
    }
  }

  for (const outputPage of pdf.getPages()) {
    drawFooter(outputPage, fonts, "This is a draft for review — not a signed transport document.");
  }
  return pdf.save();
}
