// The event catalogue: one published list of everything GainingDocx emits.
//
// This file is the contract. The webhook signup UI, the `/v1/events` endpoint,
// the developer documentation and the delivery engine all read from here, so a
// new event type cannot ship documented-but-not-sent or sent-but-undocumented.
//
// Event names are `resource.past_tense_verb` and are permanent. Renaming one
// breaks every customer filter silently — a receiver subscribed to a name that
// no longer exists gets no error, just silence — so a superseded event is
// deprecated in place, never renamed.

export const INTEGRATION_EVENTS = [
  {
    type: "document.received",
    summary: "A file arrived by upload, email-in or API and is queued for parsing.",
    fires: "Once per document, before any extraction work begins.",
    data: { document_id: "uuid", source: "upload | email | api", source_filename: "string|null", shipment_id: "uuid|null" },
  },
  {
    type: "document.parsing_started",
    summary: "Extraction began on a received document.",
    fires: "Once per parse attempt, including retries after a failure.",
    data: { document_id: "uuid", document_type: "string", page_count: "integer|null" },
  },
  {
    type: "document.parsed",
    summary: "Extraction and deterministic validation completed successfully.",
    fires: "Once per successful parse. Carries the validation summary, not the full field set — retrieve the document for that.",
    data: { document_id: "uuid", document_type: "string", shipment_id: "uuid|null", reference: "string|null", quality_score: "number|null", validation_errors: "integer" },
  },
  {
    type: "document.failed",
    summary: "A document could not be parsed.",
    fires: "After the final extraction attempt fails. The document stays in the workspace for manual handling.",
    data: { document_id: "uuid", reference: "string|null", reason: "string|null" },
  },
  {
    type: "document.review_required",
    summary: "A parsed document needs a person before it can be trusted downstream.",
    fires: "When validation or matching flags the document, or when a low-confidence field needs confirmation.",
    data: { document_id: "uuid", shipment_id: "uuid|null", reason: "string", open_discrepancies: "integer" },
  },
  {
    type: "document.approved",
    summary: "A reviewer approved the document's extracted values.",
    fires: "On reviewer approval. This is the event to write back to a TMS or accounting system.",
    data: { document_id: "uuid", shipment_id: "uuid|null", approved_by: "string|null", document_type: "string" },
  },
  {
    type: "document.corrected",
    summary: "A reviewer changed one or more extracted field values.",
    fires: "On every save of a correction, with the fields that changed.",
    data: { document_id: "uuid", shipment_id: "uuid|null", fields: "string[]", corrected_by: "string|null" },
  },
  {
    type: "shipment.created",
    summary: "A shipment record was opened.",
    fires: "When a document is linked to a reference that has no existing shipment.",
    data: { shipment_id: "uuid", reference: "string|null", bl_number: "string|null", bill_level: "string" },
  },
  {
    type: "shipment.matched",
    summary: "Cross-document matching ran across a shipment's documents.",
    fires: "After every matching pass, whether or not it found anything.",
    data: { shipment_id: "uuid", documents_compared: "integer", fields_compared: "integer", critical: "integer", warnings: "integer" },
  },
  {
    type: "discrepancy.created",
    summary: "A cross-document check found a mismatch.",
    fires: "Once per new discrepancy, carrying both conflicting values and their source documents.",
    data: { discrepancy_id: "uuid", shipment_id: "uuid", severity: "red | amber", field: "string", value_a: "string|null", value_b: "string|null", doc_a: "uuid|null", doc_b: "uuid|null", message: "string|null" },
  },
  {
    type: "discrepancy.resolved",
    summary: "A reviewer closed a discrepancy.",
    fires: "On resolution, with the outcome and the note the reviewer left.",
    data: { discrepancy_id: "uuid", shipment_id: "uuid", resolution_status: "string|null", resolved_by: "string|null", note: "string|null" },
  },
  {
    type: "report.generated",
    summary: "A discrepancy report or export was produced.",
    fires: "When a report is generated by a person or by the API.",
    data: { shipment_id: "uuid|null", format: "string", document_count: "integer" },
  },
  {
    type: "integration.delivery_failed",
    summary: "A delivery to one of your own destinations exhausted its retries.",
    fires: "When a delivery becomes dead-lettered. Never sent to the destination that failed, to avoid a notification loop.",
    data: { delivery_id: "uuid", endpoint_id: "uuid", failed_event_type: "string", attempts: "integer", last_error: "string|null" },
  },
  {
    type: "hs.reviewed",
    summary: "An HS code suggestion was accepted or overridden.",
    fires: "On each HS review decision.",
    data: { document_id: "uuid", line_index: "integer", hs_code: "string|null", decision: "string" },
  },
  {
    type: "charge.alert",
    summary: "A demurrage, detention or free-time deadline is approaching.",
    fires: "Daily, for each shipment inside its alert window.",
    data: { shipment_id: "uuid", alert_type: "string", free_until: "date", days_remaining: "integer" },
  },
  {
    type: "review.updated",
    summary: "A document's review state changed.",
    fires: "On assignment, status change or reviewer note.",
    data: { shipment_id: "uuid", document_id: "uuid|null", status: "string" },
  },
  {
    type: "export.approval",
    summary: "An export approval was requested or decided.",
    fires: "On request and again on the decision.",
    data: { shipment_id: "uuid", approval_id: "uuid|null", status: "string" },
  },
] as const;

export type IntegrationEventType = (typeof INTEGRATION_EVENTS)[number]["type"];

export const EVENT_TYPES = INTEGRATION_EVENTS.map((event) => event.type) as readonly IntegrationEventType[];

/**
 * Events that mean "something is wrong and a person should look now".
 *
 * A destination set to `critical` receives only these. Chat channels are the
 * reason this exists: a Slack channel that pings on every parsed document is
 * muted within a week, and then the critical ones are missed too.
 */
export const CRITICAL_EVENT_TYPES: readonly IntegrationEventType[] = [
  "document.failed",
  "document.review_required",
  "discrepancy.created",
  "charge.alert",
  "integration.delivery_failed",
];

export function isCriticalEvent(type: IntegrationEventType, data: Record<string, unknown>): boolean {
  // An amber discrepancy is a warning, not an incident. Filtering on the event
  // name alone would make the "critical only" setting useless for the single
  // event type customers care most about.
  if (type === "discrepancy.created") return data.severity === "red";
  return CRITICAL_EVENT_TYPES.includes(type);
}

export function eventDefinition(type: string) {
  return INTEGRATION_EVENTS.find((event) => event.type === type) ?? null;
}

export function isIntegrationEvent(value: string): value is IntegrationEventType {
  return EVENT_TYPES.includes(value as IntegrationEventType);
}
